INSERT INTO Lernsets (name, description, type) VALUES
('Shopping', 'Vokabeln zum Thema Shopping', 'standard'),
('Healthy Lifestyle', 'Vokabeln zum Thema Healthy Lifestyle', 'standard');

-- Vokabeln für Lernset ID = 9
INSERT INTO vokabeln (lernset_id, deutsch, fremdsprache) VALUES
(6, 'zufrieden', 'to satisfy'),
(6, 'Grundbedürfnisse', 'basic necessities'),
(6, 'Ware', 'goods'),
(6, 'örtlich', 'local'),
(6, 'StandinhaberIn', 'stallholder'),
(6, 'Produkt', 'produce'),
(6, 'handgemacht', 'handmade'),
(6, 'importieren', 'to import'),
(6, 'GeschäftsinhaberIn', 'shopkeeper'),
(6, 'SchlachterIn', 'butcher'),
(6, 'SchneiderIn', 'tailor'),
(6, 'Werkstätte', 'workshop'),
(6, 'VerbraucherIn', 'consumer'),
(6, 'Geschäft', 'high-street shop'),
(6, 'etwas', 'to desire something'),
(6, 'in', 'to mass-produce'),
(6, 'Kette', 'chain'),
(6, 'Verteilung', 'distribution'),
(6, 'Hersteller', 'manufacturer'),
(6, 'GroßhändlerIn', 'wholesaler'),
(6, 'in', 'in bulk'),
(6, 'verteilen', 'to distribute'),
(6, 'Lager', 'warehouse'),
(6, 'EinzelhändlerIn', 'retailer'),
(6, 'Filiale', 'chain store'),
(6, 'Fachgeschäft', 'speciality shop/store'),
(6, 'Inventar', 'inventory'),
(6, 'raten', 'to advise'),
(6, 'Einzelhandelsgeschäft', 'retail outlet'),
(6, 'Kauf-', 'department store'),
(6, 'Supermarkt', 'superstore'),
(6, 'übernehmen', 'to take over'),
(6, 'führen', 'to stock'),
(6, 'Schnäppchen', 'bargain'),
(6, 'Einkaufszentrum', 'retail park'),
(6, 'Wagen', 'trolley'),
(6, 'Gang', 'aisle'),
(6, 'Kassa', 'checkout'),
(6, 'KassiererIn', 'cashier'),
(6, 'Kauf', 'purchase'),
(6, 'Quittung', 'receipt'),
(6, 'Kreditkarte', 'to insert a credit card'),
(6, 'bequem', 'in the comfort of your own home'),
(6, 'abgetragen', 'worn out'),
(6, 'Preis-Leistungs-Verhältnis', 'value for money'),
(6, 'den', 'to convert the price'),
(6, 'Versandkosten', 'shipping costs'),
(6, 'Zahlungsschutz', 'payment protection'),
(6, 'Paket', 'parcel'),
(6, 'selten', 'rarely'),
(6, 'gelegentlich', 'occasionally');

-- Vokabeln für Lernset ID = 10
INSERT INTO vokabeln (lernset_id, deutsch, fremdsprache) VALUES
(7, 'Essgewohnheiten', 'eating habits'),
(7, 'Kohlenhydrate', 'carbs'),
(7, 'ausgewogene', 'balanced diet'),
(7, 'Nährstoffe', 'nutrients'),
(7, 'sich', 'to feel run down'),
(7, 'Eisen', 'iron'),
(7, 'im', 'in the healthy range'),
(7, 'zunehmen', 'to gain weight'),
(7, 'Modediät', 'fad diet'),
(7, 'Getreide', 'grains'),
(7, 'massig', 'bulky'),
(7, 'Vollkorn', 'wholegrain'),
(7, 'enthalten', 'to contain'),
(7, 'empfehlen', 'to recommend'),
(7, 'Mangel', 'to lack sthg.'),
(7, 'behaupten', 'to claim'),
(7, 'abhängig', 'to depend'),
(7, 'gesättigte', 'saturated fat'),
(7, 'biologische', 'organic produce'),
(7, 'Ausgesetztsein', 'exposure'),
(7, 'ankurbeln', 'to boost'),
(7, 'gemäßigt', 'moderate'),
(7, 'anspruchsvoll', 'demanding'),
(7, 'profitieren', 'to benefit'),
(7, 'niedriges', 'low self-esteem'),
(7, 'Erfolgserlebnis', 'sense of achievement'),
(7, 'Stolz', 'pride'),
(7, 'Stoffwechsel', 'metabolism'),
(7, 'beschleunigen', 'to speed up'),
(7, 'Krankheit', 'disease'),
(7, 'gefährdet', 'to be at risk of'),
(7, 'Zustand', 'condition'),
(7, 'bereitstellen', 'to provide'),
(7, 'Gliedmaßen', 'limbs'),
(7, 'Unterleib', 'abdomen'),
(7, 'Gelenke', 'joints'),
(7, 'beugen', 'to bend'),
(7, 'das', 'reduce the risk of'),
(7, 'Untersuchung', 'examination'),
(7, 'schmerzend', 'sore'),
(7, 'sich', 'to prove to be'),
(7, 'Ballaststoffe', 'dietary fibre'),
(7, 'Belastung', 'exposure'),
(7, 'landwirtschaftlich', 'agricultural'),
(7, 'Eiweiß', 'protein'),
(7, 'übergewichtig', 'obese'),
(7, '7alt', 'ancient'),
(7, 'erklären', 'to declare'),
(7, 'ablehnen', 'to refuse'),
(7, 'Anfrage', 'enquiry'),